# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"Z\n\x12\x43heckAccessRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x17\n\x0frepository_name\x18\x02 \x01(\t\x12\x19\n\x11organization_name\x18\x03 \x01(\t\"&\n\x13\x43heckAccessResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x32I\n\rAccessControl\x12\x38\n\x0b\x43heckAccess\x12\x13.CheckAccessRequest\x1a\x14.CheckAccessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKACCESSREQUEST']._serialized_start=17
  _globals['_CHECKACCESSREQUEST']._serialized_end=107
  _globals['_CHECKACCESSRESPONSE']._serialized_start=109
  _globals['_CHECKACCESSRESPONSE']._serialized_end=147
  _globals['_ACCESSCONTROL']._serialized_start=149
  _globals['_ACCESSCONTROL']._serialized_end=222
# @@protoc_insertion_point(module_scope)
